export enum DataTestIdsEnum {
  addressShard = 'addressShard',
  addressInput = 'addressInput',
  balance = 'balance',
  cancelButton = 'cancelButton',
  decodedMessage = 'decodedMessage',
  encodedMessage = 'encodedMessage',
  heroTag = 'heroTag',
  messageSignature = 'messageSignature',
  nftExplorerLink = 'nftExplorerLink',
  nftFormattedAmount = 'nftFormattedAmount',
  privateKeyInput = 'privateKeyInput',
  receiverLink = 'receiverLink',
  receiverShard = 'receiverShard',
  senderLink = 'senderLink',
  senderShard = 'senderShard',
  shardFromLink = 'shardFromLink',
  shardToLink = 'shardToLink',
  submitButton = 'submitButton',
  tokenExplorerLink = 'tokenExplorerLink',
  tokenFormattedAmount = 'tokenFormattedAmount',
  transactionHash = 'transactionHash',
  transactionLink = 'transactionLink',
  transactionMethod = 'transactionMethod',
  transactionReceiver = 'transactionReceiver',
  transactionSender = 'transactionSender',
  transactionValue = 'transactionValue'
}
